import { appTheme } from '@/shared/constants/theme';
import { StyleSheet } from 'react-native';

export const planningStyles = StyleSheet.create({
  mainContainer: { flex: 1, backgroundColor: appTheme.colors.background },
  topHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: appTheme.colors.background,
  },
  headerTitle: {
    color: appTheme.colors.white,
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 1,
  },
  activePlanBadge: {
    color: appTheme.colors.textSecondary,
    fontSize: 11,
    fontWeight: '600',
    marginTop: 2,
  },
  headerActions: { flexDirection: 'row', gap: 6 },
  presetButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: appTheme.colors.surfaceElevated,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 6,
    gap: 4,
  },
  presetButtonText: { color: appTheme.colors.white, fontWeight: '700', fontSize: 11 },
  contentBody: { paddingHorizontal: 16, paddingBottom: 130, paddingTop: 4 },

  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 18,
    marginBottom: 10,
  },
  splitTitle: {
    color: appTheme.colors.textSecondary,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
  },
  splitSummary: {
    color: appTheme.colors.textPrimary,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.3,
  },

  // Blocks
  blockRow: { gap: 8, paddingRight: 8 },
  blockChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: appTheme.colors.surfaceElevated,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: appTheme.colors.borderStrong,
    minWidth: 128,
  },
  blockChipActive: { borderColor: appTheme.colors.accent },
  blockAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: appTheme.colors.background,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: appTheme.colors.borderStrong,
  },
  blockAvatarActive: {
    backgroundColor: 'rgba(255, 159, 10, 0.15)',
    borderColor: appTheme.colors.accent,
  },
  blockAvatarText: { color: appTheme.colors.textTertiary, fontSize: 13, fontWeight: '900' },
  blockAvatarTextActive: { color: appTheme.colors.accent },
  blockChipLabel: {
    color: appTheme.colors.textTertiary,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.4,
  },
  blockChipLabelActive: { color: appTheme.colors.white },
  blockChipMeta: {
    color: appTheme.colors.textMuted,
    fontSize: 9,
    fontWeight: '600',
    marginTop: 1,
  },
  addBlockChip: {
    width: 44,
    height: 56,
    borderRadius: 12,
    backgroundColor: appTheme.colors.surfaceElevated,
    borderWidth: 1,
    borderColor: appTheme.colors.borderStrong,
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
  },

  blockDetailHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 20,
    marginBottom: 14,
  },
  iconGhostButton: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: appTheme.colors.surfaceElevated,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: appTheme.colors.borderStrong,
  },
  selectedText: {
    color: appTheme.colors.white,
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  exerciseCount: {
    color: appTheme.colors.textPrimary,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.5,
    marginTop: 2,
  },

  workoutList: { width: '100%' },
  exerciseCard: {
    backgroundColor: appTheme.colors.surfaceElevated,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 14,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: appTheme.colors.borderStrong,
  },
  cardInfo: { flex: 1, justifyContent: 'center' },
  cardExerciseName: {
    color: appTheme.colors.white,
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 3,
  },
  cardMuscleGroupMainList: {
    color: appTheme.colors.textSecondary,
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  deleteCardButton: { paddingLeft: 14, justifyContent: 'center' },
  stepperContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: appTheme.colors.background,
    borderRadius: 8,
    padding: 2,
    borderWidth: 1,
    borderColor: appTheme.colors.borderStrong,
  },
  stepperButton: {
    backgroundColor: appTheme.colors.surfaceElevated,
    width: 30,
    height: 30,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepperValueContainer: { width: 44, alignItems: 'center' },
  stepperValue: { color: appTheme.colors.white, fontSize: 14, fontWeight: '800' },
  stepperLabel: {
    color: appTheme.colors.textMuted,
    fontSize: 8,
    fontWeight: '700',
    textTransform: 'uppercase',
    marginTop: -2,
  },
  emptyState: {
    alignItems: 'center',
    marginTop: 30,
    marginBottom: 14,
    gap: 10,
  },
  emptyStateText: { color: appTheme.colors.muted, fontSize: 13, fontWeight: '600' },

  addExerciseInlineButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: appTheme.colors.background,
    borderRadius: 10,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: appTheme.colors.borderStrong,
    borderStyle: 'dashed',
  },
  addExerciseInlineText: {
    color: appTheme.colors.white,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.5,
  },

  // Weekly split
  splitDivider: {
    height: 1,
    backgroundColor: appTheme.colors.borderStrong,
    marginTop: 24,
  },
  presetRow: { gap: 8, paddingBottom: 4 },
  presetDayButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: appTheme.colors.white,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  presetDayButtonText: {
    color: appTheme.colors.textInverse,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.3,
  },
  dayGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  daySplitChip: {
    alignItems: 'center',
    gap: 4,
    backgroundColor: appTheme.colors.surfaceElevated,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: appTheme.colors.borderStrong,
    minWidth: 46,
  },
  daySplitLabel: {
    color: appTheme.colors.textSecondary,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  daySplitBadge: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: appTheme.colors.background,
    justifyContent: 'center',
    alignItems: 'center',
  },
  daySplitBadgeActive: { backgroundColor: appTheme.colors.white },
  daySplitBadgeText: { color: appTheme.colors.textMuted, fontSize: 12, fontWeight: '900' },
  daySplitBadgeTextActive: { color: appTheme.colors.textInverse },

  footerActions: {
    position: 'absolute',
    bottom: 128,
    left: 16,
    right: 16,
  },
  saveMainButton: {
    backgroundColor: appTheme.colors.textPrimary,
    height: 54,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  saveMainButtonText: {
    color: appTheme.colors.textInverse,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 1,
  },

  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 20,
  },
  modalTitle: {
    color: appTheme.colors.white,
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  closeModalHeaderBtn: { padding: 4 },
  input: {
    width: '100%',
    backgroundColor: appTheme.colors.background,
    color: appTheme.colors.white,
    padding: 16,
    borderRadius: 8,
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: appTheme.colors.borderStrong,
  },
  confirmSaveButton: {
    backgroundColor: appTheme.colors.white,
    width: '100%',
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 12,
  },
  confirmSaveText: {
    color: appTheme.colors.textInverse,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  cancelText: {
    color: appTheme.colors.textSecondary,
    fontWeight: '700',
    fontSize: 12,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  emptyPlansText: {
    color: appTheme.colors.muted,
    paddingVertical: 20,
    fontSize: 13,
    fontWeight: '600',
  },
  planItemCard: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: appTheme.colors.background,
    paddingHorizontal: 14,
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: appTheme.colors.borderStrong,
  },
  planItemCardActive: { borderColor: appTheme.colors.textPrimary },
  planItemName: {
    color: appTheme.colors.textTertiary,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  planItemNameActive: { color: appTheme.colors.textPrimary },
  confirmDeleteBadge: {
    backgroundColor: appTheme.colors.danger,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
  },
  confirmDeleteText: {
    color: appTheme.colors.white,
    fontSize: 11,
    fontWeight: '800',
  },
  modalSubtitle: {
    color: appTheme.colors.textSecondary,
    fontSize: 11,
    fontWeight: '500',
    marginTop: 2,
  },
  filterContainer: { flexDirection: 'row', marginBottom: 16, height: 34 },
  filterChip: {
    backgroundColor: appTheme.colors.background,
    paddingHorizontal: 12,
    borderRadius: 6,
    marginRight: 6,
    borderWidth: 1,
    borderColor: appTheme.colors.borderStrong,
    justifyContent: 'center',
  },
  filterChipActive: {
    backgroundColor: appTheme.colors.textPrimary,
    borderColor: appTheme.colors.textPrimary,
  },
  filterChipText: {
    color: appTheme.colors.textSecondary,
    fontSize: 11,
    fontWeight: '700',
  },
  filterChipTextActive: { color: appTheme.colors.textInverse },
  mainListPrBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 159, 10, 0.1)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    gap: 4,
  },
  mainListPrText: {
    color: appTheme.colors.accent,
    fontSize: 9,
    fontWeight: '700',
  },
  assignOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: appTheme.colors.background,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: appTheme.colors.borderStrong,
  },
  assignOptionBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: appTheme.colors.surfaceElevated,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: appTheme.colors.borderStrong,
  },
  assignOptionBadgeText: { color: appTheme.colors.textMuted, fontSize: 13, fontWeight: '900' },
  assignOptionText: {
    color: appTheme.colors.white,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  flex1: { flex: 1 },
  prRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  fullWidthMaxHeight: { width: '100%', maxHeight: 280 },
  fullWidth: { width: '100%' },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: appTheme.colors.surfaceElevated,
    borderRadius: 8,
    paddingHorizontal: 12,
    marginBottom: 10,
    gap: 8,
  },
  searchInput: {
    flex: 1,
    color: appTheme.colors.white,
    fontSize: 14,
    paddingVertical: 10,
  },
});
