import { appTheme } from '@/shared/constants/theme';
import { StyleSheet, TextStyle, ViewStyle } from 'react-native';

export const planningStyles = StyleSheet.create({
  mainContainer: { flex: 1, backgroundColor: appTheme.colors.background } satisfies ViewStyle,
  activePlanBadge: {
    color: appTheme.colors.textSecondary,
    fontSize: 11,
    fontWeight: '600',
    marginTop: 2,
  } satisfies TextStyle,
  headerActions: { flexDirection: 'row', gap: 6 } satisfies ViewStyle,
  presetButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: appTheme.colors.surfaceElevated,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 6,
    gap: 4,
  } satisfies ViewStyle,
  presetButtonText: {
    color: appTheme.colors.textPrimary,
    fontWeight: '700',
    fontSize: 11,
  } satisfies TextStyle,
  contentBody: {
    paddingHorizontal: appTheme.spacing.lg,
    paddingBottom: 130,
    paddingTop: 4,
  } satisfies ViewStyle,

  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 18,
    marginBottom: 10,
  } satisfies ViewStyle,
  splitTitle: {
    color: appTheme.colors.textSecondary,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
  } satisfies TextStyle,
  splitSummary: {
    color: appTheme.colors.textPrimary,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.3,
  } satisfies TextStyle,

  // Blocks
  blockRow: { gap: 8, paddingRight: 8 } satisfies ViewStyle,
  blockChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: appTheme.colors.surfaceElevated,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: appTheme.colors.borderStrong,
    minWidth: 128,
  } satisfies ViewStyle,
  blockChipActive: { borderColor: appTheme.colors.textPrimary } satisfies ViewStyle,
  blockAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: appTheme.colors.background,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: appTheme.colors.borderStrong,
  } satisfies ViewStyle,
  blockAvatarActive: {
    backgroundColor: appTheme.colors.surfaceElevated,
    borderColor: appTheme.colors.textPrimary,
  } satisfies ViewStyle,
  blockAvatarText: {
    color: appTheme.colors.textTertiary,
    fontSize: 13,
    fontWeight: '900',
  } satisfies TextStyle,
  blockAvatarTextActive: { color: appTheme.colors.textPrimary } satisfies TextStyle,
  blockChipLabel: {
    color: appTheme.colors.textTertiary,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.4,
  } satisfies TextStyle,
  blockChipLabelActive: { color: appTheme.colors.textPrimary } satisfies TextStyle,
  blockChipMeta: {
    color: appTheme.colors.textMuted,
    fontSize: 9,
    fontWeight: '600',
    marginTop: 1,
  } satisfies TextStyle,
  addBlockChip: {
    width: 44,
    height: 56,
    borderRadius: 12,
    backgroundColor: appTheme.colors.surfaceElevated,
    borderWidth: 1,
    borderColor: appTheme.colors.borderStrong,
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
  } satisfies ViewStyle,

  blockDetailHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 20,
    marginBottom: 14,
  } satisfies ViewStyle,
  iconGhostButton: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: appTheme.colors.surfaceElevated,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: appTheme.colors.borderStrong,
  } satisfies ViewStyle,
  selectedText: {
    color: appTheme.colors.textPrimary,
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: 0.5,
  } satisfies TextStyle,
  exerciseCount: {
    color: appTheme.colors.textPrimary,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.5,
    marginTop: 2,
  } satisfies TextStyle,

  workoutList: { width: '100%' } satisfies ViewStyle,
  exerciseCard: {
    backgroundColor: appTheme.colors.surfaceElevated,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 14,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: appTheme.colors.borderStrong,
  } satisfies ViewStyle,
  cardInfo: { flex: 1, justifyContent: 'center' } satisfies ViewStyle,
  cardExerciseName: {
    color: appTheme.colors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 3,
  } satisfies TextStyle,
  cardMuscleGroupMainList: {
    color: appTheme.colors.textSecondary,
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  } satisfies TextStyle,
  deleteCardButton: { paddingLeft: 14, justifyContent: 'center' } satisfies ViewStyle,
  stepperContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: appTheme.colors.background,
    borderRadius: 8,
    padding: 2,
    borderWidth: 1,
    borderColor: appTheme.colors.borderStrong,
  } satisfies ViewStyle,
  stepperButton: {
    backgroundColor: appTheme.colors.surfaceElevated,
    width: 30,
    height: 30,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  } satisfies ViewStyle,
  stepperValueContainer: { width: 44, alignItems: 'center' } satisfies ViewStyle,
  stepperValue: {
    color: appTheme.colors.textPrimary,
    fontSize: 14,
    fontWeight: '800',
  } satisfies TextStyle,
  stepperLabel: {
    color: appTheme.colors.textMuted,
    fontSize: 8,
    fontWeight: '700',
    textTransform: 'uppercase',
    marginTop: -2,
  } satisfies TextStyle,
  emptyState: {
    alignItems: 'center',
    marginTop: 30,
    marginBottom: 14,
    gap: 10,
  } satisfies ViewStyle,
  emptyStateText: {
    color: appTheme.colors.muted,
    fontSize: 13,
    fontWeight: '600',
  } satisfies TextStyle,

  addExerciseInlineButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: appTheme.colors.background,
    borderRadius: 10,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: appTheme.colors.borderStrong,
    borderStyle: 'dashed',
  } satisfies ViewStyle,
  addExerciseInlineText: {
    color: appTheme.colors.textPrimary,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.5,
  } satisfies TextStyle,

  // Weekly split
  splitDivider: {
    height: 1,
    backgroundColor: appTheme.colors.borderStrong,
    marginTop: 24,
  } satisfies ViewStyle,
  dayGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  } satisfies ViewStyle,
  daySplitChip: {
    alignItems: 'center',
    gap: 4,
    backgroundColor: appTheme.colors.surfaceElevated,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: appTheme.colors.borderStrong,
    minWidth: 46,
  } satisfies ViewStyle,
  daySplitLabel: {
    color: appTheme.colors.textSecondary,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.3,
  } satisfies TextStyle,
  daySplitBadge: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: appTheme.colors.background,
    justifyContent: 'center',
    alignItems: 'center',
  } satisfies ViewStyle,
  daySplitBadgeActive: { backgroundColor: appTheme.colors.textPrimary } satisfies ViewStyle,
  daySplitBadgeText: {
    color: appTheme.colors.textMuted,
    fontSize: 12,
    fontWeight: '900',
  } satisfies TextStyle,
  daySplitBadgeTextActive: { color: appTheme.colors.textInverse } satisfies TextStyle,

  footerActions: {
    position: 'absolute',
    bottom: 128,
    left: appTheme.spacing.lg,
    right: appTheme.spacing.lg,
  } satisfies ViewStyle,
  saveMainButton: {
    backgroundColor: appTheme.colors.textPrimary,
    height: 54,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  } satisfies ViewStyle,
  saveMainButtonText: {
    color: appTheme.colors.textInverse,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 1,
  } satisfies TextStyle,

  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 20,
  } satisfies ViewStyle,
  modalTitle: {
    color: appTheme.colors.textPrimary,
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 0.5,
  } satisfies TextStyle,
  closeModalHeaderBtn: { padding: 4 } satisfies ViewStyle,
  input: {
    width: '100%',
    backgroundColor: appTheme.colors.background,
    color: appTheme.colors.textPrimary,
    padding: 16,
    borderRadius: 8,
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: appTheme.colors.borderStrong,
  } satisfies TextStyle,
  confirmSaveButton: {
    backgroundColor: appTheme.colors.textPrimary,
    width: '100%',
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 12,
  } satisfies ViewStyle,
  confirmSaveText: {
    color: appTheme.colors.textInverse,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0.5,
  } satisfies TextStyle,
  confirmSaveButtonDisabled: {
    opacity: 0.5,
  } satisfies ViewStyle,
  orphanSubtitle: {
    color: appTheme.colors.textSecondary,
    fontSize: 11,
    fontWeight: '500',
    lineHeight: 16,
    marginBottom: 12,
  } satisfies TextStyle,
  orphanBlockRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: appTheme.colors.background,
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: appTheme.colors.borderStrong,
  } satisfies ViewStyle,
  orphanBlockText: {
    color: appTheme.colors.textPrimary,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.3,
  } satisfies TextStyle,
  cancelText: {
    color: appTheme.colors.textSecondary,
    fontWeight: '700',
    fontSize: 12,
    textAlign: 'center',
    letterSpacing: 0.5,
  } satisfies TextStyle,
  emptyPlansText: {
    color: appTheme.colors.muted,
    paddingVertical: 20,
    fontSize: 13,
    fontWeight: '600',
  } satisfies TextStyle,
  planItemCard: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: appTheme.colors.background,
    paddingHorizontal: 14,
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: appTheme.colors.borderStrong,
  } satisfies ViewStyle,
  planItemCardActive: { borderColor: appTheme.colors.textPrimary } satisfies ViewStyle,
  planItemName: {
    color: appTheme.colors.textTertiary,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.5,
  } satisfies TextStyle,
  planItemNameActive: { color: appTheme.colors.textPrimary } satisfies TextStyle,
  confirmDeleteBadge: {
    backgroundColor: appTheme.colors.danger,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
  } satisfies ViewStyle,
  confirmDeleteText: {
    color: appTheme.colors.textPrimary,
    fontSize: 11,
    fontWeight: '800',
  } satisfies TextStyle,
  modalSubtitle: {
    color: appTheme.colors.textSecondary,
    fontSize: 11,
    fontWeight: '500',
    marginTop: 2,
  } satisfies TextStyle,
  assignOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: appTheme.colors.background,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: appTheme.colors.borderStrong,
  } satisfies ViewStyle,
  assignOptionBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: appTheme.colors.surfaceElevated,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: appTheme.colors.borderStrong,
  } satisfies ViewStyle,
  assignOptionBadgeText: {
    color: appTheme.colors.textMuted,
    fontSize: 13,
    fontWeight: '900',
  } satisfies TextStyle,
  assignOptionText: {
    color: appTheme.colors.textPrimary,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.3,
  } satisfies TextStyle,
  flex1: { flex: 1 } satisfies ViewStyle,
  prRow: { flexDirection: 'row', alignItems: 'center', gap: 8 } satisfies ViewStyle,
  fullWidthMaxHeight: { width: '100%', maxHeight: 280 } satisfies ViewStyle,
});
