import { ExerciseData } from '@/types/workout';

export type { MuscleGroup, ExerciseData } from '@/types/workout';

export const EXERCISES_LIST: ExerciseData[] = [
  // ─── PEITO ─────────────
  {
    id: 'p1',
    name: 'Supino Reto',
    muscleGroup: 'Peito',
    mechanic: 'Composto',
    equipment: 'Barra',
    defaultSets: 4,
  },
  {
    id: 'p2',
    name: 'Supino Inclinado',
    muscleGroup: 'Peito',
    mechanic: 'Composto',
    equipment: 'Halter',
    defaultSets: 4,
  },
  {
    id: 'p3',
    name: 'Crossover',
    muscleGroup: 'Peito',
    mechanic: 'Isolado',
    equipment: 'Polia',
    defaultSets: 3,
  },
  {
    id: 'p4',
    name: 'Voador',
    muscleGroup: 'Peito',
    mechanic: 'Isolado',
    equipment: 'Máquina',
    defaultSets: 3,
  },
  {
    id: 'p5',
    name: 'Supino Declinado',
    muscleGroup: 'Peito',
    mechanic: 'Composto',
    equipment: 'Barra',
    defaultSets: 4,
  },
  {
    id: 'p6',
    name: 'Supino com Halteres',
    muscleGroup: 'Peito',
    mechanic: 'Composto',
    equipment: 'Halter',
    defaultSets: 4,
  },

  // ─── COSTAS ─────────────
  {
    id: 'c1',
    name: 'Puxada Aberta na Polia',
    muscleGroup: 'Costas',
    mechanic: 'Composto',
    equipment: 'Polia',
    defaultSets: 4,
  },
  {
    id: 'c2',
    name: 'Remada Baixa',
    muscleGroup: 'Costas',
    mechanic: 'Composto',
    equipment: 'Polia',
    defaultSets: 4,
  },
  {
    id: 'c3',
    name: 'Remada Curvada',
    muscleGroup: 'Costas',
    mechanic: 'Composto',
    equipment: 'Barra',
    defaultSets: 4,
  },
  {
    id: 'c4',
    name: 'Pulldown',
    muscleGroup: 'Costas',
    mechanic: 'Isolado',
    equipment: 'Polia',
    defaultSets: 3,
  },
  {
    id: 'c5',
    name: 'Remada Unilateral',
    muscleGroup: 'Costas',
    mechanic: 'Composto',
    equipment: 'Halter',
    defaultSets: 3,
  },
  {
    id: 'c6',
    name: 'Puxada Fechada',
    muscleGroup: 'Costas',
    mechanic: 'Composto',
    equipment: 'Polia',
    defaultSets: 4,
  },
  {
    id: 'c7',
    name: 'Barra Fixa',
    muscleGroup: 'Costas',
    mechanic: 'Composto',
    equipment: 'Peso Corporal',
    defaultSets: 3,
  },

  // ─── OMBROS ─────────────
  {
    id: 'o1',
    name: 'Desenvolvimento',
    muscleGroup: 'Ombro',
    mechanic: 'Composto',
    equipment: 'Halter',
    defaultSets: 4,
  },
  {
    id: 'o2',
    name: 'Elevação Lateral',
    muscleGroup: 'Ombro',
    mechanic: 'Isolado',
    equipment: 'Halter',
    defaultSets: 4,
  },
  {
    id: 'o3',
    name: 'Crucifixo Invertido',
    muscleGroup: 'Ombro',
    mechanic: 'Isolado',
    equipment: 'Halter',
    defaultSets: 3,
  },
  {
    id: 'o4',
    name: 'Arnold Press',
    muscleGroup: 'Ombro',
    mechanic: 'Composto',
    equipment: 'Halter',
    defaultSets: 4,
  },
  {
    id: 'o5',
    name: 'Elevação Frontal',
    muscleGroup: 'Ombro',
    mechanic: 'Isolado',
    equipment: 'Halter',
    defaultSets: 3,
  },
  {
    id: 'o6',
    name: 'Desenvolvimento na Máquina',
    muscleGroup: 'Ombro',
    mechanic: 'Composto',
    equipment: 'Máquina',
    defaultSets: 4,
  },

  // ─── BÍCEPS ─────────────
  {
    id: 'b1',
    name: 'Rosca Direta',
    muscleGroup: 'Bíceps',
    mechanic: 'Isolado',
    equipment: 'Barra',
    defaultSets: 3,
  },
  {
    id: 'b2',
    name: 'Rosca Alternada Inclinada',
    muscleGroup: 'Bíceps',
    mechanic: 'Isolado',
    equipment: 'Halter',
    defaultSets: 3,
  },
  {
    id: 'b3',
    name: 'Rosca Martelo',
    muscleGroup: 'Bíceps',
    mechanic: 'Isolado',
    equipment: 'Halter',
    defaultSets: 3,
  },
  {
    id: 'b4',
    name: 'Rosca Scott',
    muscleGroup: 'Bíceps',
    mechanic: 'Isolado',
    equipment: 'Máquina',
    defaultSets: 3,
  },
  {
    id: 'b5',
    name: 'Rosca Concentrada',
    muscleGroup: 'Bíceps',
    mechanic: 'Isolado',
    equipment: 'Halter',
    defaultSets: 3,
  },

  // ─── TRÍCEPS ─────────────
  {
    id: 't1',
    name: 'Tríceps Corda',
    muscleGroup: 'Tríceps',
    mechanic: 'Isolado',
    equipment: 'Polia',
    defaultSets: 4,
  },
  {
    id: 't2',
    name: 'Tríceps Testa',
    muscleGroup: 'Tríceps',
    mechanic: 'Isolado',
    equipment: 'Barra',
    defaultSets: 3,
  },
  {
    id: 't3',
    name: 'Tríceps Francês',
    muscleGroup: 'Tríceps',
    mechanic: 'Isolado',
    equipment: 'Halter',
    defaultSets: 3,
  },
  {
    id: 't4',
    name: 'Tríceps na Polia',
    muscleGroup: 'Tríceps',
    mechanic: 'Isolado',
    equipment: 'Polia',
    defaultSets: 3,
  },
  {
    id: 't5',
    name: 'Mergulho entre Bancos',
    muscleGroup: 'Tríceps',
    mechanic: 'Composto',
    equipment: 'Peso Corporal',
    defaultSets: 3,
  },

  // ─── QUADRÍCEPS ─────────────
  {
    id: 'q1',
    name: 'Agachamento Livre',
    muscleGroup: 'Quadríceps',
    mechanic: 'Composto',
    equipment: 'Barra',
    defaultSets: 4,
  },
  {
    id: 'q2',
    name: 'Leg Press 45Â°',
    muscleGroup: 'Quadríceps',
    mechanic: 'Composto',
    equipment: 'Máquina',
    defaultSets: 4,
  },
  {
    id: 'q3',
    name: 'Cadeira Extensora',
    muscleGroup: 'Quadríceps',
    mechanic: 'Isolado',
    equipment: 'Máquina',
    defaultSets: 4,
  },
  {
    id: 'q4',
    name: 'Agachamento Hack',
    muscleGroup: 'Quadríceps',
    mechanic: 'Composto',
    equipment: 'Máquina',
    defaultSets: 4,
  },
  {
    id: 'q5',
    name: 'Avanço com Halteres',
    muscleGroup: 'Quadríceps',
    mechanic: 'Composto',
    equipment: 'Halter',
    defaultSets: 3,
  },

  // ─── POSTERIOR ─────────────
  {
    id: 'po1',
    name: 'Cadeira Flexora',
    muscleGroup: 'Posterior',
    mechanic: 'Isolado',
    equipment: 'Máquina',
    defaultSets: 4,
  },
  {
    id: 'po2',
    name: 'Stiff',
    muscleGroup: 'Posterior',
    mechanic: 'Composto',
    equipment: 'Barra',
    defaultSets: 3,
  },
  {
    id: 'po3',
    name: 'Cadeira RomanÄƒ',
    muscleGroup: 'Posterior',
    mechanic: 'Composto',
    equipment: 'Máquina',
    defaultSets: 4,
  },
  {
    id: 'po4',
    name: 'Good Morning',
    muscleGroup: 'Posterior',
    mechanic: 'Composto',
    equipment: 'Barra',
    defaultSets: 3,
  },
  {
    id: 'po5',
    name: 'Peso Morto Convencional',
    muscleGroup: 'Posterior',
    mechanic: 'Composto',
    equipment: 'Barra',
    defaultSets: 4,
  },

  // ─── PANTURRILHA ─────────────
  {
    id: 'pa1',
    name: 'Gêmeos em Pé',
    muscleGroup: 'Panturrilha',
    mechanic: 'Isolado',
    equipment: 'Máquina',
    defaultSets: 4,
  },
  {
    id: 'pa2',
    name: 'Gêmeos Sentado',
    muscleGroup: 'Panturrilha',
    mechanic: 'Isolado',
    equipment: 'Máquina',
    defaultSets: 4,
  },
  {
    id: 'pa3',
    name: 'Elevação de Panturrilha no Leg Press',
    muscleGroup: 'Panturrilha',
    mechanic: 'Isolado',
    equipment: 'Máquina',
    defaultSets: 4,
  },

  // ─── ABDÔMEN ─────────────
  {
    id: 'a1',
    name: 'Abdominal Supra',
    muscleGroup: 'Abdômen',
    mechanic: 'Isolado',
    equipment: 'Peso Corporal',
    defaultSets: 3,
  },
  {
    id: 'a2',
    name: 'Prancha',
    muscleGroup: 'Abdômen',
    mechanic: 'Isolado',
    equipment: 'Peso Corporal',
    defaultSets: 3,
  },
  {
    id: 'a3',
    name: 'Elevação de Pernas',
    muscleGroup: 'Abdômen',
    mechanic: 'Isolado',
    equipment: 'Peso Corporal',
    defaultSets: 3,
  },
  {
    id: 'a4',
    name: 'Abdominal na Polia',
    muscleGroup: 'Abdômen',
    mechanic: 'Isolado',
    equipment: 'Polia',
    defaultSets: 3,
  },

  // ─── Antebraço ─────────────
  {
    id: 'an1',
    name: 'Rosca de Punho',
    muscleGroup: 'Antebraço',
    mechanic: 'Isolado',
    equipment: 'Barra',
    defaultSets: 3,
  },
  {
    id: 'an2',
    name: 'Rosca de Punho com Halter',
    muscleGroup: 'Antebraço',
    mechanic: 'Isolado',
    equipment: 'Halter',
    defaultSets: 3,
  },
  {
    id: 'an3',
    name: "Farmer's Walk",
    muscleGroup: 'Antebraço',
    mechanic: 'Composto',
    equipment: 'Halter',
    defaultSets: 3,
  },

  // ─── TRAPÉZIO ─────────────
  {
    id: 'tr1',
    name: 'Encolhimento com Halteres',
    muscleGroup: 'Trapézio',
    mechanic: 'Isolado',
    equipment: 'Halter',
    defaultSets: 4,
  },
  {
    id: 'tr2',
    name: 'Encolhimento com Barra',
    muscleGroup: 'Trapézio',
    mechanic: 'Isolado',
    equipment: 'Barra',
    defaultSets: 4,
  },
  {
    id: 'tr3',
    name: 'Encolhimento na Polia',
    muscleGroup: 'Trapézio',
    mechanic: 'Isolado',
    equipment: 'Polia',
    defaultSets: 3,
  },
];
